version: "3.8"
services:
  backend-java:
    build:
      context: ./backend-java
    container_name: backendJavaContainer 
    ports:
      - "8080:8080"
    volumes:
      - ./backend-java:/app
    networks:
      - app-network

  backend-go:
    build:
      context: ./backend-go
    container_name: backendGoContainer 
    ports:
      - "8081:8080"
    volumes:
      - ./backend-go:/app
    networks:
      - app-network

  frontend-dart:
    build:
      context: ./frontend-dart
    container_name: frontendDartContainer
    ports:
      - "8082:80"
    volumes:
      - ./frontend-dart/web:/usr/share/nginx/html/web:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
